export const copy = {
  brand: {
    name: "Anything Download",
    tagline: "Any format. Any device. No account.",
    positioning: "No ads. No sign-up. Files delete themselves.",
    honest: "Download and process publicly accessible files and media you have permission to use.",
  },
  nav: {
    skip: "Skip to main content",
    tools: "Tools",
    extension: "Extension",
    cta: "Start now",
    about: "About",
    home: "Home",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    theme: "Color theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
  },
  home: {
    badge: "Private by default",
    heading: "Paste anything.",
    headingAccent: "Get exactly what you need.",
    lead: "Give it a public link or a file. Anything Download works out what can honestly be done with it, then does it: download, convert, compress or extract. No account, and files delete themselves.",
    verbs: ["Download", "Convert", "Compress", "Extract"],
    quickEyebrow: "Quick actions",
    popularHeading: "Popular tools",
    popularLead: "One click to the jobs people do most.",
    allTools: "Browse all tools",
    stepsEyebrow: "How it works",
    stepsTitle: "Three steps. No detours.",
    stepsLead: "Every step shows you what is really happening on the server.",
    steps: [
      {
        title: "Paste or upload",
        body: "Drop in a public link, or a file from your device. Nothing is sent until you press Analyze.",
      },
      {
        title: "Pick a tool",
        body: "The server inspects the source and offers only the tools that actually work for it.",
      },
      {
        title: "Download",
        body: "Watch real progress, preview the result, download it. It deletes itself soon after.",
      },
    ],
    ecosystemEyebrow: "Tool ecosystem",
    ecosystemTitle: "One workspace. Every kind of file.",
    ecosystemLead:
      "Video, audio, images, PDFs and web pages, handled by focused tools that each do one job well.",
    demoEyebrow: "See it work",
    demoTitle: "From link to file, in plain sight.",
    demoLead: "An example of the journey. Real jobs show the server's actual state at every step.",
    whyEyebrow: "Trust",
    whyTitle: "Built to be trusted with your files.",
    whyLead: "Privacy isn't a setting here. It's how the service is built.",
    why: [
      {
        title: "Private by default",
        body: "No tracking scripts, no ads, no analytics. Logs keep no full links.",
      },
      {
        title: "No account",
        body: "Nothing to sign up for, nothing to remember, nothing tied to you.",
      },
      {
        title: "Files delete themselves",
        body: "Uploads and results are removed automatically after a short window.",
      },
      {
        title: "Honest about limits",
        body: "Private, protected or unsupported content is refused, and we say exactly why.",
      },
      {
        title: "Secure by design",
        body: "Private network addresses are blocked, and every request is size- and rate-limited.",
      },
    ],
    extensionEyebrow: "Chrome extension",
    extensionTitle: "Analyze the page you're on.",
    extensionBody:
      "Find public images, videos, audio and PDFs from any page in one click, then open them in Anything Download.",
    useCasesEyebrow: "Made for",
    useCasesTitle: "Whatever you're working on.",
    discoveryEyebrow: "Tool discovery",
    discoveryTitle: "Find the right tool in seconds.",
    discoveryLead: "Search by format or action, or browse by category.",
    ctaTitle: "Ready when you are.",
    ctaLead: "Paste a public link to see what's possible. It takes a few seconds.",
    ctaLabel: "Paste a link to analyze",
    ctaButton: "Start analyzing",
    groups: {
      video: "Video",
      image: "Image",
      pdf: "PDF",
      audio: "Audio",
      web: "Web",
    },
    trust: ["No ads", "No account", "Files auto-delete"],
  },
  widget: {
    label: "Paste a URL or upload a file",
    urlPlaceholder: "https://example.com/file.mp4",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    dropTitle: "Drop a file here",
    dropHint: "Or choose a file from your device.",
    chooseFile: "Choose file",
    chooseFiles: "Choose files",
    removeFile: "Remove file",
    selectedFile: "Selected file",
    uploadProgress: "Uploading",
    textLabel: "Text or URL to encode",
    textPlaceholder: "Enter the text or URL for the QR code",
    run: "Start",
    running: "Working…",
    cancel: "Cancel",
    retry: "Try again",
    availableOperations: "Available operations",
    chooseOperation: "Choose an operation",
    optionsHeading: "Options",
    cannotProcess: "Can't process this source",
    youtubeTitle: "Why YouTube links often fail here",
    youtubeBody:
      "YouTube blocks many cloud servers with a “confirm you're not a bot” check. We never try to get around it.",
    youtubeTips: [
      "Your own video? Download the original from YouTube Studio (Content, then the ⋮ menu, then Download) and upload it here.",
      "Direct video links and file uploads always work.",
      "Running Anything Download on your own computer uses your normal connection.",
    ],
    youtubeSelfHost: "How to run it yourself",
    platformNote:
      "YouTube currently blocks many servers, so YouTube links may be refused. Direct links and uploads always work.",
    alternativesHeading: "Other tools you can use",
    alternativesLead:
      "This source cannot be processed. These tools work with a different kind of input.",
    noTools: "No operations are available for this source.",
    toolUnavailable:
      "This tool is not enabled on this server. It may require FFmpeg, a browser worker, or platform extractors.",
    resultsHeading: "Analysis",
    jobHeading: "Job status",
    processing: "Processing…",
    queued: "Queued",
  },
  analysis: {
    source: "Source",
    type: "Type",
    platform: "Platform",
    size: "Size",
    duration: "Duration",
    dimensions: "Dimensions",
    filename: "Filename",
    mime: "Type",
    resources: "Found on page",
    warnings: "Notes",
    restrictions: "Restrictions",
  },
  result: {
    heading: "Your result",
    download: "Download",
    delete: "Delete now",
    deleteConfirmTitle: "Delete this file now?",
    deleteConfirm:
      "This removes the result immediately. You will not be able to download it again.",
    deleteConfirmAction: "Delete",
    deleted: "This file has been deleted.",
    expired: "This result has expired and was deleted.",
    failed: "This job did not finish.",
    cancelled: "This job was cancelled.",
    notReady: "This job has not finished yet.",
    expiry: (label: string) => `Your file will be automatically deleted in ${label}.`,
    expiryNow: "Your file is about to be deleted.",
    format: "Format",
    size: "Size",
    filename: "Filename",
    notes: "Notes",
    dataHeading: "Details",
    preview: "Preview",
    backHome: "Back to home",
    sourcePreview: "Source preview",
  },
  tools: {
    heading: "Tools",
    lead: "A catalogue of operations this service can run on public URLs and files you upload.",
    fallbackNote:
      "The live catalogue could not be loaded. This list is a static reference only; operations are not guaranteed to be available.",
    unavailable: "Not available on this server",
    howItWorks: "How it works",
    accepts: "What it accepts",
    willNot: "What it will not do",
    related: "Related tools",
  },
  legal: {
    extension: {
      title: "Chrome extension",
      description:
        "An optional companion for Chrome: analyze the page you are on and open it in Anything Download. What it does, the permissions it uses, and what it never collects.",
      homeLink: "Get the Chrome extension",
      homeNote: "Optional. Everything on this site works without it.",
    },
    about: {
      title: "About",
      description: "What Anything Download is, and what it is not.",
    },
    privacy: {
      title: "Privacy",
      description: "How this service handles URLs, uploads, and temporary results.",
    },
    terms: {
      title: "Terms",
      description: "Acceptable use and limits of this free utility.",
    },
    copyright: {
      title: "Copyright",
      description: "You must have permission to process the files and media you submit.",
    },
    security: {
      title: "Security",
      description: "How this service is designed and how to report a vulnerability.",
    },
    contact: {
      title: "Contact",
      description: "How to reach the operator of this instance.",
    },
  },
  offline: {
    title: "You are offline",
    description:
      "This page is cached so you can still read about the service. Analyzing URLs and downloading files needs a network connection.",
    back: "Try the homepage",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "This page does not exist.",
    notFoundLead: "The address may be mistyped, or the page was removed.",
    jobNotFound: "This job does not exist or has expired.",
  },
  a11y: {
    status: "Status",
    loading: "Loading",
    themeToggle: "Switch color theme",
  },
  footer: {
    rights: "Free, open-source software.",
    groups: { product: "Product", legal: "Trust & legal" },
    links: {
      about: "About",
      privacy: "Privacy",
      terms: "Terms",
      copyright: "Copyright",
      security: "Security",
      contact: "Contact",
      tools: "Tools",
      extension: "Chrome extension",
    },
  },
  options: {
    format: "Format",
    quality: "Quality",
    level: "Compression level",
    bitrate: "Bitrate",
    target: "Output format",
    width: "Width",
    height: "Height",
    percent: "Scale percent",
    fit: "Fit",
    pages: "Pages",
    mode: "Split mode",
    chunkSize: "Pages per file",
    dpi: "DPI",
    imageFormat: "Image format",
    keepMetadata: "Keep metadata",
    qrFormat: "QR format",
    scale: "Scale",
    border: "Border",
    errorCorrection: "Error correction",
    fullPage: "Capture the full page",
    pageSize: "Page size",
    landscape: "Landscape",
    printBackground: "Print background",
    startSeconds: "Start (seconds)",
    durationSeconds: "Duration (seconds)",
    fps: "Frames per second",
    atSeconds: "Timestamp (seconds)",
    lossless: "Lossless",
    maxImages: "Maximum images",
    minBytes: "Skip images smaller than (bytes)",
    marginPt: "Margin (points)",
  },
  notes: {
    remuxed_without_reencoding: "The file was remuxed without re-encoding.",
    output_not_smaller: "The output was not smaller than the source.",
    metadata_removed: "Embedded metadata was removed.",
    transparency_flattened: "Transparent pixels were flattened onto a white background.",
    png_quantized_to_256_colors: "The PNG was reduced to 256 colors to save space.",
    images_recompressed: "Embedded images were recompressed.",
    some_images_skipped: "Some images could not be downloaded and were skipped.",
    no_text_layer: "This PDF has no text layer. The exported file may be empty.",
  },
  phases: {
    queued: "Queued",
    downloading: "Downloading",
    processing: "Processing",
    rendering: "Rendering",
    uploading: "Uploading",
    analyzing: "Analyzing",
  },
} as const;

export function noteLabel(code: string): string {
  const known = copy.notes[code as keyof typeof copy.notes];
  return known ?? code.replace(/_/g, " ");
}

export function phaseLabel(phase: string): string {
  const known = copy.phases[phase as keyof typeof copy.phases];
  return known ?? phase.replace(/[_-]+/g, " ");
}
